#### Preamble
MACHINEOVERRIDES =. "${@['', 'genesyszu-5ev:']['genesyszu-5ev' != '${MACHINE}']}"
#### Regular settings follow

require conf/machine/zynqmp-ev-generic.conf

#### No additional settings should be after the Postamble
#### Postamble
PACKAGE_EXTRA_ARCHS:append = "${@['', ' genesyszu_5ev']['genesyszu-5ev' != "${MACHINE}"]}"


