#### Preamble
MACHINEOVERRIDES =. "${@['', 'genesyszu-3eg:']['genesyszu-3eg' != '${MACHINE}']}"
#### Regular settings follow

require conf/machine/zynqmp-eg-generic.conf

#### No additional settings should be after the Postamble
#### Postamble
PACKAGE_EXTRA_ARCHS:append = "${@['', ' genesyszu_3eg']['genesyszu-3eg' != "${MACHINE}"]}"


